# Generated by Django 6.1.1 on 2026-09-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('registration_year', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price amount in ₹', max_digits=12)),
                ('price_negotiable', models.BooleanField(default=True, verbose_name='Price Negotiable')),
                ('km_driven', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('AMT', 'AMT'), ('CVT', 'CVT'), ('DCT', 'DCT')], default='Manual', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('owners', models.PositiveIntegerField(default=1)),
                ('insurance_valid', models.BooleanField(default=True, verbose_name='Insurance Valid')),
                ('location', models.CharField(default='Surat, Gujarat', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('sold', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cars/main/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
