# Generated by Django 6.1.1 on 2026-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Petrol + CNG', 'Petrol + CNG'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=20),
        ),
    ]
