# Generated by Django 6.1.1 on 2026-09-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(default='Bhavnagar, Gujarat', max_length=100),
        ),
    ]
