# Generated by Django 6.1.1 on 2026-09-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='advertisements/')),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership_name', models.CharField(default='Sitaram Cars', max_length=150)),
                ('contact_name', models.CharField(default='YASH PARMAR', max_length=100)),
                ('phone', models.CharField(default='8140832399', max_length=20)),
                ('whatsapp_number', models.CharField(default='918140832399', max_length=20)),
                ('about_text', models.TextField(default='Welcome to Sitaram Cars. We provide quality certified used cars with transparent deals and trusted service.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('dealer_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='cars.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
